.\PreliminaryJudge.exe -m maps\map1.txt -l WARN -s 0 "java -jar ..\out\main.jar"
.\PreliminaryJudge.exe -m maps\map2.txt -l WARN -s 0 "java -jar ..\out\main.jar" 
.\PreliminaryJudge.exe -m maps\map-3.8.txt -l WARN -s 0 "java -jar ..\out\main.jar" 
.\PreliminaryJudge.exe -m maps\map-3.9.txt -l WARN -s 0 "java -jar ..\out\main.jar" 
.\PreliminaryJudge.exe -m maps\map-3.10.txt -l WARN -s 0 "java -jar ..\out\main.jar" 
.\PreliminaryJudge.exe -m maps\map-3.11.txt -l WARN -s 0 "java -jar ..\out\main.jar" 
.\PreliminaryJudge.exe -m maps\map-3.12.txt -l WARN -s 0 "java -jar ..\out\main.jar" 
.\PreliminaryJudge.exe -m maps\map-3.13.txt -l WARN -s 0 "java -jar ..\out\main.jar" 